#!/bin/env /usr/bin/ruby
require 'rubygems'
require 'sinatra/activerecord'
require 'sinatra'
require 'net/ldap'
require 'socket'
require 'timeout'
require 'sinatra/session'
require 'yaml'
require 'uri'
set :environment, :production
set :port, 80
$config = YAML.load_file('/etc/IPtoDHCP.conf')
require "#{$config[:path]}/baseengine/auth.rb"
Dir["#{$config[:path]}/baseengine/*.rb"].each {|file| require file }
